### ISSUE TITLE
Gangway 2.0.0

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/gangway#33]
A couple of things have come up that warrant a major release:

- [x] Fix awkward `route` API (#32, PR #36)
- [x] Require Promise polyfill instead of including own (#31, PR #37)
- [x] Distinguish between absolute and relative paths (#34, PR #38)
- [x] Update changelog

Is there anything else we want to do while we're considering a breaking release?

**Comment by nhunzaker** [comment]
Cut!
